#!/bin/bash

# VPS Deployment Guide for Aarya Clothing Authentication Fixes
# This script guides you through deploying the OTP and authentication fixes to your VPS

echo "=========================================="
echo "VPS Deployment Guide - Authentication Fixes"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 Prerequisites:${NC}"
echo "1. SSH access to your VPS"
echo "2. Git installed on VPS"
echo "3. Docker and Docker Compose installed"
echo "4. Domain pointing to VPS (aaryaclothing.cloud)"
echo ""

echo -e "${BLUE}🔧 Step 1: Connect to VPS${NC}"
echo "SSH into your VPS:"
echo "ssh root@your-vps-ip"
echo ""

echo -e "${BLUE}📁 Step 2: Navigate to Project Directory${NC}"
echo "cd /path/to/your/project"
echo "or if it's in /root:"
echo "cd /root/Aarya_Clothing"
echo ""

echo -e "${BLUE}🔄 Step 3: Pull Latest Changes${NC}"
echo "Make sure you're on the testing branch:"
echo "git checkout testing"
echo ""
echo "Pull the latest changes:"
echo "git pull origin testing"
echo ""

echo -e "${BLUE}🐳 Step 4: Review Docker Configuration${NC}"
echo "Check your docker-compose.yml:"
echo "cat docker-compose.yml | grep -A 10 -B 5 'frontend'"
echo ""
echo "Key things to verify:"
echo "- Frontend service is configured"
echo "- Core service has SMTP settings"
echo "- Environment variables are set"
echo ""

echo -e "${BLUE}🔍 Step 5: Check Environment Variables${NC}"
echo "Make sure your .env file has the correct settings:"
echo "cat .env"
echo ""
echo "Critical variables for OTP:"
echo "- SMTP_HOST=smtp.gmail.com"
echo "- SMTP_PORT=587"
echo "- SMTP_USER=razorrag.official@gmail.com"
echo "- SMTP_PASSWORD=dbvn-cxml-ahoc-ndmy"
echo "- OTP_CODE_LENGTH=6"
echo ""

echo -e "${BLUE}🛑 Step 6: Stop Current Services${NC}"
echo "Stop all running containers:"
echo "docker-compose down"
echo ""

echo -e "${BLUE}🧹 Step 7: Clean Up (Optional)${NC}"
echo "Remove old images and containers:"
echo "docker system prune -f"
echo ""

echo -e "${BLUE}🏗️ Step 8: Build and Start Services${NC}"
echo "Build and start all services:"
echo "docker-compose up --build -d"
echo ""

echo -e "${BLUE}⏳ Step 9: Wait for Services to Start${NC}"
echo "Check service status:"
echo "docker-compose ps"
echo ""
echo "Wait for all services to be 'healthy' (may take 2-3 minutes)"
echo ""

echo -e "${BLUE}🔍 Step 10: Check Service Logs${NC}"
echo "Check core service logs:"
echo "docker-compose logs core"
echo ""
echo "Check frontend logs:"
echo "docker-compose logs frontend"
echo ""

echo -e "${BLUE}🧪 Step 11: Test Authentication Endpoints${NC}"
echo "Test core service health:"
echo "curl http://localhost:8001/api/v1/health"
echo ""
echo "Test through nginx (external):"
echo "curl https://aaryaclothing.cloud/api/v1/health"
echo ""

echo -e "${BLUE}📧 Step 12: Test OTP Functionality${NC}"
echo "Run the OTP test script on VPS:"
echo "./test-otp-endpoint.sh"
echo ""
echo "Or test manually:"
echo "curl -X POST https://aaryaclothing.cloud/api/v1/auth/send-otp \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\":\"test@example.com\",\"otp_type\":\"email_verification\",\"purpose\":\"verify\"}'"
echo ""

echo -e "${BLUE}🌐 Step 13: Test Frontend${NC}"
echo "Visit your website:"
echo "https://aaryaclothing.cloud/login"
echo ""
echo "Test the following:"
echo "1. Registration with strong password"
echo "2. Login with email"
echo "3. Login with username"
echo "4. OTP verification (optional)"
echo "5. Password reset"
echo ""

echo -e "${BLUE}🔧 Step 14: Troubleshooting Common Issues${NC}"
echo ""
echo "If frontend not updating:"
echo "  docker-compose restart frontend"
echo "  docker-compose logs frontend"
echo ""
echo "If OTP not working:"
echo "  docker-compose logs core | grep -i otp"
echo "  docker-compose logs core | grep -i email"
echo "  Check Redis: docker-compose exec redis redis-cli keys 'otp:*'"
echo ""
echo "If database issues:"
echo "  docker-compose logs postgres"
echo "  docker-compose exec postgres psql -U postgres -d aarya_clothing -c 'SELECT COUNT(*) FROM users;'"
echo ""

echo -e "${BLUE}📊 Step 15: Monitor Performance${NC}"
echo "Check container resource usage:"
echo "docker stats"
echo ""
echo "Check disk space:"
echo "df -h"
echo ""
echo "Check memory usage:"
echo "free -h"
echo ""

echo "=========================================="
echo "🎯 Deployment Summary"
echo "=========================================="
echo ""
echo -e "${GREEN}✅ What's Been Deployed:${NC}"
echo "- Enhanced login page with dual email/username support"
echo "- Complete registration flow with password validation"
echo "- Optional OTP verification system"
echo "- Auto-login after registration"
echo "- Improved error messages and loading states"
echo "- Comprehensive test scripts"
echo ""
echo -e "${YELLOW}⚠️ Important Notes:${NC}"
echo "- Frontend builds may take 5-10 minutes on first deployment"
echo "- OTP emails are sent via Gmail SMTP"
echo "- Redis stores OTP codes and sessions"
echo "- All services restart automatically on failure"
echo ""
echo -e "${BLUE}🔗 Useful Commands:${NC}"
echo "- View logs: docker-compose logs -f [service]"
echo "- Restart service: docker-compose restart [service]"
echo "- Check status: docker-compose ps"
echo "- Access container: docker-compose exec [service] sh"
echo ""
echo "=========================================="
